name: Build Sphinx docs

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-sphinx-docs:
    name: Build Sphinx docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install ivcurves requirements
        working-directory: main
        run: pip3 install -r ivcurves/requirements.txt
      - name: Install Sphinx docs requirements
        working-directory: main/docs/sphinx
        run: |
          pip3 install -U sphinx==5.0.2
          pip3 install -r requirements.txt
      - name: Generate Sphinx docs test case images
        working-directory: main
        run: python3 ivcurves/precise.py --save-images docs/sphinx/source/_images/test_cases
      - name: Copy IV Curve JSON Schema to _static files
        working-directory: main
        run: cp ivcurves/ivcurve_jsonschema.json docs/sphinx/source/_static/.
      - name: Rebuild Sphinx docs html
        working-directory: main/docs/sphinx
        run: make html
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      - name: Copy Sphinx build to gh-pages
        run: cp -r main/docs/sphinx/build/html/. gh-pages/.
      - name: Commit and push docs to gh-pages
        working-directory: gh-pages
        run: |
          git config user.name 'GitHub'
          git config user.email 'github@ivcurves'
          git add -A .
          git commit -m 'Update Sphinx docs'
          git push origin HEAD:gh-pages --force

