name: Pytest

on:
  push:

jobs:
  run-pytest:
    name: Run Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install ivcurves testing dependencies
        run: pip3 install -e .[testing]  # the install is editable because the GitHub workflow util .py scripts are not included in the ivcurves package install to site packages
      - name: Run Pytest
        run: pytest ivcurves/tests

