name: Record scores

on:
  pull_request_target:
    branches: main
    types:
      - closed

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PR_AUTHOR: ${{ github.event.pull_request.user.login }}

jobs:
  score-submission:
    uses: ./.github/workflows/score-submission.yaml

  record-scores:
    name: Record scores
    runs-on: ubuntu-latest
    needs: score-submission
    if: ${{ needs.score-submission.outputs.run-scorer == 'true' && github.event.pull_request.merged == true && github.ref_type == 'branch' && github.ref_name == 'main' && github.repository_owner == 'cwhanse' }}
    steps:
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install ivcurves
        run: pip3 install .
      - name: Download overall_scores.csv
        uses: actions/download-artifact@v3
        with:
          name: overall_scores.csv
      - name: Validate and record scores
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 .github/workflows/utils/record_scores.py
               --pr-author ${{ env.PR_AUTHOR }}
               --pr-number ${{ env.PR_NUMBER }}
               --pr-closed-at ${{ github.event.pull_request.closed_at }}
               --merge-commit $(gh pr view ${{ env.PR_NUMBER }} -q .mergeCommit.oid --json mergeCommit)
               --submission-main ${{ needs.score-submission.outputs.submission-main }}
               --overall-scores-path overall_scores.csv
               --database-path docs/sphinx/source/scores_database.json
      - name: Commit and push scores database
        id: commit-scores
        run: |
          git config user.name 'GitHub'
          git config user.email 'github@ivcurves'
          git add docs/sphinx/source/scores_database.json
          git commit -m 'Update scores database'
          git push origin main

  build-sphinx-docs:
    needs:
      - score-submission
      - record-scores
    if: ${{ needs.score-submission.outputs.run-scorer == 'true' }}
    uses: ./.github/workflows/build-sphinx-docs.yaml

