name: Score submission

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  read-pr-config:
    name: Read pull request config
    runs-on: ubuntu-latest
    outputs:
      contributor: ${{ steps.save-env.outputs.contributor }} # GitHub username of committer or pull request author
      run-scorer: ${{ steps.save-env.outputs.run-scorer }} # Boolean to run the run-scorer job
      requirements-filename: ${{ steps.save-env.outputs.requirements-filename }} # filename of the submission's Pip requirements file (usually requirements.txt)
      requirements-path: ${{ steps.save-env.outputs.requirements-path }} # path to the parent directory that contains requirements-filename
      submission-main-filename: ${{ steps.save-env.outputs.submission-main-filename }} # filename of the file that should be executed by run-scorer
      submission-main-path: ${{ steps.save-env.outputs.submission-main-path }} # path to the parent directory that contains submission-main-filename
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Save pull request contributor username
        id: save-pr-author
        run: echo '::set-output name=contributor::${{ github.event.pull_request.user.login }}'
      - name: Save GitHub actor username
        id: save-github-actor
        if: ${{ steps.save-pr-author.outputs.contributor == '' }}
        run: echo '::set-output name=contributor::${{ github.actor }}'
      - name: Set the contributor environment variable
        env:
          CONTRIBUTOR: ${{ join(steps.*.outputs.contributor, '') }}
        run: echo 'CONTRIBUTOR=${{ env.CONTRIBUTOR }}' >> ${{ github.env }}
      - name: Set pr_config.json entries as environment variables
        run: python3 .github/workflows/utils/print_json_as_env.py
               submissions/${{ env.CONTRIBUTOR }}/pr_config.json
               --validate-pr-config
               --split-path-variables
             >> ${{ github.env }}
      - name: Save scorer environment to job output
        id: save-env
        run: |
          echo '::set-output name=contributor::${{ env.CONTRIBUTOR }}'
          echo '::set-output name=run-scorer::${{ env.RUN_SCORER }}'
          echo '::set-output name=requirements-filename::${{ env.REQUIREMENTS_FILENAME }}'
          echo '::set-output name=requirements-path::${{ env.REQUIREMENTS_PATH }}'
          echo '::set-output name=submission-main-filename::${{ env.SUBMISSION_MAIN_FILENAME }}'
          echo '::set-output name=submission-main-path::${{ env.SUBMISSION_MAIN_PATH }}'
      - name: Upload pr_config.json to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pr_config.json
          path: submissions/${{ env.CONTRIBUTOR }}/pr_config.json

  run-scorer:
    name: Run scorer
    runs-on: ubuntu-latest
    needs: read-pr-config
    if: ${{ needs.read-pr-config.outputs.run-scorer == 'true' }}
    env:
      CONTRIBUTOR: ${{ needs.read-pr-config.outputs.contributor }}
      REQUIREMENTS_FILENAME: ${{ needs.read-pr-config.outputs.requirements-filename }}
      REQUIREMENTS_PATH: ${{ needs.read-pr-config.outputs.requirements-path }}
      SUBMISSION_MAIN_FILENAME: ${{ needs.read-pr-config.outputs.submission-main-filename }}
      SUBMISSION_MAIN_PATH: ${{ needs.read-pr-config.outputs.submission-main-path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install ivcurves requirements
        run: pip3 install -r ivcurves/requirements.txt
      - name: Install submission requirements
        working-directory: submissions/${{ env.CONTRIBUTOR }}/${{ env.REQUIREMENTS_PATH }}
        run: pip3 install -r ${{ env.REQUIREMENTS_FILENAME }}
      - name: Run submission
        working-directory: submissions/${{ env.CONTRIBUTOR }}/${{ env.SUBMISSION_MAIN_PATH }}
        run: python3 ${{ env.SUBMISSION_MAIN_FILENAME }}
      - name: Run scorer
        working-directory: submissions/${{ env.CONTRIBUTOR }}
        run: python3 ../../ivcurves/compare_curves.py . --csv-output-path .
      - name: Save scores to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: overall_scores.csv
          path: submissions/${{ env.CONTRIBUTOR }}/overall_scores.csv

